site_name: ScopusSurveyAPI
site_url: http://127.0.0.1:8001/scopus-survey-api
site_description: Web API for bibliographic survey of Scopus articles
site_author: mauprogramador
repo_name: mauprogramador/scopus-survey-api
repo_url: https://github.com/mauprogramador/scopus-survey-api
edit_uri: '/docs'
theme:
  name: material
  custom_dir: docs/overrides
  language: en
  logo: assets/img/favicon.png
  favicon: assets/img/favicon.png
  icon:
    repo: fontawesome/brands/github
  features:
    - navigation.instant.progress
    - navigation.indexes
    - navigation.footer
    - navigation.path
    - navigation.top
    - search.highlight
    - search.suggest
    - content.code.select
    - content.code.copy
    - content.tooltips
    - toc.follow
  palette:
  - media: '(prefers-color-scheme: dark)'
    scheme: slate
    primary: orange
    accent: pink
    toggle:
      icon: material/lightbulb-outline
      name: Switch to dark mode
  - media: '(prefers-color-scheme: light)'
    scheme: default
    primary: orange
    accent: pink
    toggle:
      icon: material/lightbulb
      name: Switch to light mode
nav:
- index.md
- requirements.md
- getting-started.md
- environment.md
- scopus-search-api.md
- scopus-abstract-retrieval-api.md
- api-limit-and-fields-and-filter.md
- responses-and-errors.md
- testing.md
- hooks-actions.md
- reference.md
- release-notes.md
- technologies.md
- license.md
- glossary.md
- contact.md
plugins:
- search:
    lang:
    - en
    - pt
- i18n:
    docs_structure: folder
    languages:
    - locale: en
      name: English (en-us)
      build: true
      default: true
    - locale: pt
      name: Português (pt-br)
      build: true
- markdownextradata:
    data: docs/assets/data
markdown_extensions:
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      options:
        custom_icons:
          - overrides/.icons
  - pymdownx.highlight:
      pygments_lang_class: true
      anchor_linenums: true
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - pymdownx.snippets
  - pymdownx.details
  - pymdownx.mark
  - pymdownx.keys
  - md_in_html
  - admonition
  - footnotes
  - attr_list
  - def_list
  - tables
  - abbr
extra:
  social:
  - icon: fontawesome/brands/github
    link: https://github.com/mauprogramador/scopus-survey-api
    name: Source code GitHub repository
  - icon: ifms
    link: https://www.ifms.edu.br/campi/campus-tres-lagoas
    name: IFMS - Campus Três Lagoas
  - icon: fontawesome/solid/envelope
    link: mailto:sir.silvabmauricio@gmail.com
    name: Developer email contact
  - icon: fontawesome/solid/user
    link: https://github.com/mauprogramador
    name: Developer GitHub profile
  - icon: fontawesome/brands/linkedin
    link: https://www.linkedin.com/in/mauricio-silva-batista-0ba90322b/
    name: Developer LinkedIn
  - icon: fontawesome/brands/x-twitter
    link: https://twitter.com/Maurcio77788085
    name: Developer X / Twitter
  - icon: fontawesome/brands/instagram
    link: https://www.instagram.com/mauricio_cap_tl/
    name: Developer Instagram
extra_css:
  - assets/css/custom.css
