name: Documentation
on:
  push:
    branches:
      - master
permissions:
  contents: write
jobs:
  documentation:
    runs-on: ubuntu-latest
    steps:

      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: Load cached venv
        uses: actions/cache@v4
        with:
          key: ${{ github.ref }}
          path: .cache

      - run: pip3 install mkdocs-material
      - run: mkdocs gh-deploy --force
